### PR TITLE
[RL][bugfix] Fixed Core Project not having build config consistent.

### PR DESCRIPTION
**Pull request by le-rich**
…onfigs

### CODE REVIEW

**Comment by imnorookie** [comment]
lgtm! :3

**Review by imnorookie — APPROVED** [review]
lgtm :3

**Review by Tissure — COMMENTED** [review]
Release x64 build doesn't build. Missing GLAD dependencies in Linker.

**Review by imnorookie — APPROVED** [review]
debug and release x64 works on my local.

lgtm :3

**Review by Tissure — APPROVED** [review]
lgtm

**Pull request merged**
