### PR TITLE
Feature/com 19 fragment shader is able to color basic primitives

### PR DESCRIPTION
**Pull request by Lukauigi**
Add shader parsing of a file, given its path.  Used for creating a shader program from vertex and fragment shaders from one file.

### CODE REVIEW

**Comment by Lukauigi** [comment]
LMK if I should delete default.frag & default.vert files.

**Review by le-rich — APPROVED** [review]

**Comment by le-rich** [comment]
Please change target to develop.

**Review by RealGoldenGeneral — APPROVED** [review]
Ran by fetching this pull request on Visual Studio 2022. Instead of showing a read triangle, which is what the master branch shows, this shows an indigo triangle.

**Review by Tissure — DISMISSED** [review]
lgtm

**Review by Tissure — APPROVED** [review]
lgtm

**Review by le-rich — APPROVED** [review]

**Pull request merged**
